# These are supported funding model platforms

github: [wwevo]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: [ecv] # Replace with a single Patreon username
custom:['https://paypal.me/wwevo'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
